// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDPTDfXz4uxqPUgwQ9PAbTPUY2JbdzwOQ',
    appId: '1:64065223454:web:7ae2d03856061394c6a70f',
    messagingSenderId: '64065223454',
    projectId: 'cashfortrash-be34f',
    authDomain: 'cashfortrash-be34f.firebaseapp.com',
    storageBucket: 'cashfortrash-be34f.firebasestorage.app',
    measurementId: 'G-N5S06WT30J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4uHNHkiATgf_Zx41-vQwWawjRT0uDwIM',
    appId: '1:64065223454:android:273f8890af155d03c6a70f',
    messagingSenderId: '64065223454',
    projectId: 'cashfortrash-be34f',
    storageBucket: 'cashfortrash-be34f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_cu20X_PsijrQR_jWoCqGiln1PSmacmw',
    appId: '1:64065223454:ios:3f82ccc2638cf465c6a70f',
    messagingSenderId: '64065223454',
    projectId: 'cashfortrash-be34f',
    storageBucket: 'cashfortrash-be34f.firebasestorage.app',
    iosBundleId: 'com.example.cashForTrash',
  );
}
